<? xml version = "1.0" encoding = "UTF-8"?>
	<plist version="1.0">
	<dict>
		<key>items</key>
		<array>
			<dict>
				<key>assets</key>
				<array>
					<dict>
						<key>kind</key>
						<string>software-package</string>
						<key>url</key>
						<string>${packageUrl}</string>
					</dict>
				</array>
				<key>metadata</key>
				<dict>
					<key>bundle-identifier</key>
					<string>${bundleId}</string>
					<key>bundle-version</key>
					<string>${bundleVersion}</string>
					<key>kind</key>
					<string>software</string>
					<key>title</key>
					<string>iOS-package</string>
				</dict>
			</dict>
		</array>
	</dict>
</plist>
