package com.baiyi.opscloud.common.constants;

/**
 * @Author baiyi
 * @Date 2021/11/12 10:23 下午
 * @Version 1.0
 */
public interface SingleTaskConstants {

    String PULL_ALIYUN_ECS_IMAGE = "PULL_ALIYUN_ECS_IMAGE";
    String PULL_ALIYUN_ECS = "PULL_ALIYUN_ECS";
    String PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE = "PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE";
    String PULL_ALIYUN_ONS_ROCKETMQ_GROUP = "PULL_ALIYUN_ONS_ROCKETMQ_GROUP";
    String PULL_ALIYUN_ONS_ROCKETMQ_TOPIC = "PULL_ALIYUN_ONS_ROCKETMQ_TOPIC";
    String PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE_TARGET_GROUP = "PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE_TARGET_GROUP";
    String PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE_TARGET_TOPIC = "PULL_ALIYUN_ONS_ROCKETMQ_INSTANCE_TARGET_TOPIC";
    String PULL_ALIYUN_ONS5_INSTANCE = "PULL_ALIYUN_ONS5_INSTANCE";
    String PULL_ALIYUN_ONS5_GROUP = "PULL_ALIYUN_ONS5_GROUP";
    String PULL_ALIYUN_ONS5_TOPIC = "PULL_ALIYUN_ONS5_TOPIC";
    String PULL_ALIYUN_RAM_ACCESS_KEY = "PULL_ALIYUN_RAM_ACCESS_KEY";
    String PULL_ALIYUN_RAM_POLICY = "PULL_ALIYUN_RAM_POLICY";
    String PULL_ALIYUN_RAM_USER = "PULL_ALIYUN_RAM_USER";
    String PULL_ALIYUN_RDS_DATABASE = "PULL_ALIYUN_RDS_DATABASE";
    String PULL_ALIYUN_RDS_INSTANCE = "PULL_ALIYUN_RDS_INSTANCE";
    String PULL_ALIYUN_REDIS_INSTANCE = "PULL_ALIYUN_REDIS_INSTANCE";
    String PULL_ALIYUN_SECURITY_GROUP = "PULL_ALIYUN_SECURITY_GROUP";
    String PULL_ALIYUN_VPC = "PULL_ALIYUN_VPC";
    String PULL_ALIYUN_VSWITCH = "PULL_ALIYUN_VSWITCH";
    String PULL_ALIYUN_ACR_INSTANCE = "PULL_ALIYUN_ACR_INSTANCE";
    String PULL_ALIYUN_ACR_NAMESPACE = "PULL_ALIYUN_ACR_NAMESPACE";
    String PULL_ALIYUN_DMS_USER = "PULL_ALIYUN_DMS_USER";
    String PUSH_ALIYUN_DMS_USER = "PUSH_ALIYUN_DMS_USER";
    String PULL_ALIYUN_DOMAIN = "PULL_ALIYUN_DOMAIN";

    String PULL_ALIYUN_DEVOPS_PROJECT = "PULL_ALIYUN_DEVOPS_PROJECT";
    String PULL_ALIYUN_DEVOPS_SPRINT = "PULL_ALIYUN_DEVOPS_SPRINT";
    String PULL_ALIYUN_DEVOPS_WORKITEM = "PULL_ALIYUN_DEVOPS_WORKITEM";

    String PULL_ALIYUN_ARMS_TRACE_APP = "PULL_ALIYUN_ARMS_TRACE_APP";

    String PULL_ANSIBLE_HOSTS = "PULL_ANSIBLE_HOSTS";
    String PULL_ANSIBLE_VERSION = "PULL_ANSIBLE_VERSION";

    String PULL_AWS_EC2 = "PULL_AWS_EC2";
    String PULL_AWS_IAM_POLICY = "PULL_AWS_IAM_POLICY";
    String PULL_AWS_IAM_USER = "PULL_AWS_IAM_USER";
    String PULL_AWS_IAM_ACCESS_KEY = "PULL_AWS_IAM_ACCESS_KEY";
    String PULL_AWS_SQS = "PULL_AWS_SQS";
    String PULL_AWS_SNS_TOPIC = "PULL_AWS_SNS_TOPIC";
    String PULL_AWS_SNS_SUBSCRIPTION = "PULL_AWS_SNS_SUBSCRIPTION";
    String PULL_AWS_DOMAIN = "PULL_AWS_DOMAIN";
    String PULL_AWS_ECR_REPOSITORY = "PULL_AWS_ECR_REPOSITORY";

    String PULL_GITLAB_GROUP = "PULL_GITLAB_GROUP";
    String PULL_GITLAB_PROJECT = "PULL_GITLAB_PROJECT";
    String PULL_GITLAB_SSH_KEY = "PULL_GITLAB_SSH_KEY";
    String PULL_GITLAB_USER = "PULL_GITLAB_USER";

    String PULL_JENKINS_COMPUTER = "PULL_JENKINS_COMPUTER";
    String PULL_JENKINS_TEMPLATE = "PULL_JENKINS_TEMPLATE";
    String PULL_JENKINS_JOB = "PULL_JENKINS_JOB";

    String PULL_KUBERNETES_NODE = "PULL_KUBERNETES_NODE";
    String PULL_KUBERNETES_DEPLOYMENT = "PULL_KUBERNETES_DEPLOYMENT";
    String PULL_KUBERNETES_SERVICE = "PULL_KUBERNETES_SERVICE";
    String PULL_KUBERNETES_NAMESPACE = "PULL_KUBERNETES_NAMESPACE";
    String PULL_KUBERNETES_POD = "PULL_KUBERNETES_POD";
    String PULL_KUBERNETES_INGRESS = "PULL_KUBERNETES_INGRESS";
    String PULL_ISTIO_VIRTUAL_SERVICE = "PULL_ISTIO_VIRTUAL_SERVICE";
    String PULL_ISTIO_DESTINATION_RULE = "PULL_ISTIO_DESTINATION_RULE";

    String PULL_LDAP_GROUP = "PULL_LDAP_GROUP";
    String PULL_LDAP_USER = "PULL_LDAP_USER";

    String PULL_NACOS_CLUSTER_NODE = "PULL_NACOS_CLUSTER_NODE";
    String PULL_NACOS_PERMISSION = "PULL_NACOS_PERMISSION";
    String PULL_NACOS_USER = "PULL_NACOS_USER";

    String PULL_NEXUS_ASSET = "PULL_NEXUS_ASSET";

    String PULL_SONAR_PROJECT = "PULL_SONAR_PROJECT";

    String PULL_TENCENT_EXMAIL_USER = "PULL_TENCENT_EXMAIL_USER";

    String PULL_ZABBIX_HOST = "PULL_ZABBIX_HOST";
    String PULL_ZABBIX_HOST_GROUP = "PULL_ZABBIX_HOST_GROUP";
    String PULL_ZABBIX_TEMPLATE = "PULL_ZABBIX_TEMPLATE";
    String PULL_ZABBIX_TRIGGER = "PULL_ZABBIX_TRIGGER";
    String PULL_ZABBIX_USER_GROUP = "PULL_ZABBIX_USER_GROUP";
    String PULL_ZABBIX_USER = "PULL_ZABBIX_USER";

    String PULL_DINGTALK_USER = "PULL_DINGTALK_USER";
    String PULL_DINGTALK_DEPARTMENT = "PULL_DINGTALK_DEPARTMENT";

    String SCAN_ASSET_BUSINESS = "SCAN_ASSET_BUSINESS";

    String PULL_HUAWEICLOUD_ECS = "PULL_HUAWEICLOUD_ECS";

    String PULL_CONSUL_SERVICE = "PULL_CONSUL_SERVICE";

    String CONSUL_ALERT_TASK = "CONSUL_ALERT_TASK";

    String PULL_METER_SPHERE_BUILD_HOOK = "PULL_METER_SPHERE_BUILD_HOOK";

    String PULL_APOLLO_APP = "PULL_APOLLO_APP";
}
