package com.baiyi.opscloud.workorder.constants;

/**
 * @Author baiyi
 * @Date 2020/4/28 10:59 上午
 * @Version 1.0
 */
public enum WorkOrderKeyConstants {

    /**
     * 工单KEY
     */
    RAM_POLICY,
    IAM_POLICY,
    AWS_IAM_UPDATE_LOGIN_PROFILE,
    ALIYUN_RAM_UPDATE_LOGIN_PROFILE,
    ONS_ROCKETMQ_TOPIC,
    ONS_ROCKETMQ_GROUP,
    ONS5_TOPIC,
    ONS5_GROUP,
    SQS,
    SNS_TOPIC,
    SNS_SUBSCRIPTION,

    SERVER_GROUP,
    APPLICATION_PERMISSION,
    // UserGroup
    VPN,
    NEXUS,
    GRAFANA,
    APOLLO,
    CONFLUENCE,
    NACOS,
    GITLAB_PROJECT,
    GITLAB_GROUP,
    SYS_EMPLOYEE_RESIGN,

    APPLICATION_SCALE_REPLICAS,
    APPLICATION_REDUCE_REPLICAS,

    KUBERNETES_CONTAINER_JVM_SPEC_CHANGES,

    // 发布
    APPLICATION_DEPLOY,
    // 新应用
    NEW_APPLICATION,
    // 配置发布
    APOLLO_RELEASE,
    // Ser发布
    SER_DEPLOY,

    APPLICATION_FINOPS_TAG,

    AWS_TRANSFER_CREATE_USER,

    KUBERNETES_ISTIO_CONFIGURATION

}